image: node:12.16

clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script: #installation
            - npm install
      - step:
          name: Deploy to Staging
          deployment: staging
          trigger: manual
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP.git HEAD
      - step:
          name: Deploy to Production
          deployment: production
          trigger: manual
          script:
            - git push https://heroku:$HEROKU_API_KEY_PROD@git.heroku.com/$HEROKU_PROD_APP.git HEAD
